### ISSUE TITLE
Enhance SIC detail

### ISSUE THREAD

**Issue by miha42-github** [miha42-github/company_dns#26]
# Introduction
SIC search actually includes additional details that could be helpful for the consumer of the service.  Therefore additional information like major group, industry group, etc will be added to the service.  Additionally other SIC endpoints will be considered to help obtain additional information about standard industry codes.

# Tasks

- [x] Add major group code to EDGAR
- [x] Add major group description to EDGAR
- [x] Add industry group code to EDGAR
- [x] Add major group endpoint(s)
- [x] Consider adding industry group endpoint(s)
- [x] Add division endpoint(s)
